server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${VAR_ENV_PROMTAIL_CLIENT}

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers
  # entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  # --log-opt tag="{{.Name}}"

  pipeline_stages:
    - json:
        expressions:
          attrs: attrs
          tag: attrs.tag
    - docker: {}
    - timestamp:
        fallback_formats:
          - RFC3339Nano
          - RFC3339
        format: Unix
        source: timestamp
    - json:
        expressions:
          level: level
    - regex:
        expression: (?P<container_name>(?:[^|]*[^|]))
        source: "tag"
    - labels:
        level:
        stream:
        container_name: