{
 "title": "tg_weather_dashboards",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "status_db ( 1 - on ,  0 - off )",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Responce - 2xx, 3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/tg_webhooks\", status=\"2xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/actions_count\", status=\"2xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/users_actions\", status=\"2xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/users_actions\", status=\"3xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/actions_count\", status=\"3xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/tg_webhooks\", status=\"3xx\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DataBase errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(database_connection_errors_total[5m])",
     "legendFormat": "database_connection_errors"
    },
    {
     "expr": "rate(database_query_errors_total[5m])",
     "legendFormat": "database_query_errors_total"
    },
    {
     "expr": "rate(database_other_errors_total[5m])",
     "legendFormat": "database_other_errors"
    },
    { "expr": "rate(data_base_runtime[5m])", "legendFormat": "data_base_runtime" }
   ]
  },
  {
   "title": "HTTP Responce - 4xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/tg_webhooks\", status=\"4xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/actions_count\", status=\"4xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/users_actions\", status=\"4xx\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Responce - 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/tg_webhooks\", status=\"5xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/actions_count\", status=\"5xx\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/users_actions\", status=\"5xx\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General and user experience errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(unknown_commands_total[5m])",
     "legendFormat": "Count of unknown commands received {instance = \"172.18.0.4:8888}"
    },
    {
     "expr": "rate(instance_errors_total[5m])",
     "legendFormat": "Count of errors by instance {instance = 172.18.0.4:8888}"
    },
    {
     "expr": "rate(user_errors_total[5m])",
     "legendFormat": "User interaction errors {instance = \"172.18.0.4:8888}"
    }
   ]
  },
  {
   "title": "external_api_error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(external_api_validation_errors[5m])",
     "legendFormat": "external_api_validation_errors"
    },
    { "expr": "rate(external_api_error[5m])", "legendFormat": "external_api_error" }
   ]
  }
 ]
}